title: Fikri's Website
description: My personal website
url: "https://fikriafik.github.io"
baseurl: ""


# Build settings

markdown: kramdown
permalink: none

port: 4000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
